# Generated by Django 3.2.5 on 2021-12-07 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
